language: python
python:
    - 2.7
    - 3.2
    - 3.4

install:
    # update aptitude
    - sudo apt-get update -y

    - sudo apt-get install -y aptitude

    # install aptitude packages
    - LDFLAGS=-lm sudo aptitude install -y $(< requirements)

    # webp - compiling from source
    - wget "https://webp.googlecode.com/files/libwebp-0.4.0.tar.gz" -O libwebp-0.4.0.tar.gz
    - tar xvzf libwebp-0.4.0.tar.gz
    - cd libwebp-0.4.0 && ./configure --enable-libwebpmux --enable-libwebpdemux --enable-libwebpdecoder && make && sudo make install; cd ..
    - sudo ldconfig

    # install python requirements
    - make setup

script:
    # finally run tests
    - make ci_test
